# Generated by Django 3.0.7 on 2020-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('equipmentID', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=30)),
                ('isSuccess', models.BooleanField(default=False)),
            ],
        ),
    ]
