# Generated by Django 3.0.7 on 2020-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_remove_user_issuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
